<div style="width:450px;margin:auto" class="page-header">
    <h1>Place Your Bet!</h1>
</div>
<div style="width:450px;margin:auto">
<img width="600" src="https://cdn.pixabay.com/photo/2018/11/19/18/19/poker-3825827_1280.jpg"><br>

<form action="login/checkuser">
<input type="text" placeholder="login" name="login"><br>
<input type="text" placeholder="******" name="password">&nbsp;<br>
<button type="button">Login</button>&nbsp;<br>
<button type="button">Register</button><br>
</form>
</div>
<?php= $result ?>
