<div style="width:450px;margin:auto" class="page-header">
   <h1>Welcome to Roulette!</h1>
</div>
<div style="width:450px;margin:auto">
<img width="350" src="https://cdn.pixabay.com/photo/2016/03/17/23/09/roulette-1264078_1280.jpg">
<form action="index/checkuser">
<input type="text" placeholder="login" name="login">
<input type="password" placeholder="*****" name="password">
<br/>
<button type="submit">Login</button>&nbsp;
<button type="button">Register</button>
</form>
</div>
<?php= $result ?>
